import { createGoogleGenerativeAI } from '@ai-sdk/google'
import { createOpenAI } from '@ai-sdk/openai'
import { generateObject, streamText, type LanguageModel } from 'ai'

/**
 * AI provider fallback layer.
 *
 * Gemini (free tier) is the PRIMARY provider. If Gemini fails for ANY reason
 * (quota exceeded, high demand, 5xx, timeout, network, etc.) we transparently
 * fall back to OpenRouter so generation keeps working.
 *
 * OpenRouter is only used when Gemini fails. If OPENROUTER_API_KEY is not
 * configured the behaviour is Gemini-only (the original error is thrown).
 *
 * Every request logs which model actually produced the response.
 *
 * NOTE: AI SDK v5's `textStream` does NOT throw on a provider error — it just
 * ends silently and reports the error via `onError`. To reliably detect a
 * Gemini failure we therefore consume `fullStream`, which surfaces the error as
 * an explicit `{ type: 'error' }` part.
 */

const google = createGoogleGenerativeAI({
    apiKey: process.env.GEMINI_API_KEY,
})

const openrouter = process.env.OPENROUTER_API_KEY
    ? createOpenAI({
          apiKey: process.env.OPENROUTER_API_KEY,
          baseURL: 'https://openrouter.ai/api/v1',
          // Optional ranking headers for the OpenRouter dashboard.
          headers: {
              'HTTP-Referer': process.env.OPENROUTER_SITE_URL ?? '',
              'X-Title': process.env.OPENROUTER_SITE_NAME ?? 'S2C',
          },
      })
    : null

const GEMINI_MODEL = process.env.GEMINI_MODEL ?? 'gemini-3.5-flash'
// OpenRouter model id (override via env). Defaults to Claude Opus 4.5.
const OPENROUTER_MODEL =
    process.env.OPENROUTER_MODEL ?? 'anthropic/claude-opus-4.5'

const PRIMARY_LABEL = `Gemini (${GEMINI_MODEL})`
const FALLBACK_LABEL = `OpenRouter (${OPENROUTER_MODEL})`

const primaryModel = (): LanguageModel => google(GEMINI_MODEL)
const fallbackModel = (): LanguageModel | null =>
    openrouter ? openrouter(OPENROUTER_MODEL) : null

const errMessage = (error: unknown): string =>
    error instanceof Error ? error.message : String(error)

const asError = (error: unknown): Error =>
    error instanceof Error ? error : new Error(String(error))

type StreamParams = Omit<Parameters<typeof streamText>[0], 'model'>

/**
 * Streams text from Gemini. If Gemini fails before producing any output (for
 * ANY reason), transparently retries the same request on OpenRouter. If Gemini
 * already started streaming text, its error propagates (we never duplicate a
 * partially-streamed response).
 *
 * Logs which model produced the response.
 */
export async function* streamTextWithFallback(
    params: StreamParams
): AsyncGenerator<string> {
    // ---- Try primary: Gemini ----
    let produced = false
    let primaryError: unknown = null

    try {
        const primary = streamText({
            ...params,
            model: primaryModel(),
            // Silence the SDK's default error dump; we handle errors ourselves.
            onError: () => {},
        })

        for await (const part of primary.fullStream) {
            if (part.type === 'text-delta') {
                produced = true
                yield part.text
            } else if (part.type === 'error') {
                primaryError = part.error
                break
            }
        }
    } catch (error) {
        primaryError = error
    }

    if (!primaryError) {
        console.log(`[ai] ✅ Response generated by: ${PRIMARY_LABEL}`)
        return
    }

    // Gemini failed. If it already streamed text we cannot cleanly switch.
    if (produced) {
        console.error(
            `[ai] ❌ ${PRIMARY_LABEL} failed mid-stream (cannot fall back): ${errMessage(primaryError)}`
        )
        throw asError(primaryError)
    }

    const fallback = fallbackModel()
    if (!fallback) {
        console.error(
            `[ai] ❌ ${PRIMARY_LABEL} failed and no OPENROUTER_API_KEY configured: ${errMessage(primaryError)}`
        )
        throw asError(primaryError)
    }

    console.warn(`[ai] ⚠️  ${PRIMARY_LABEL} failed: ${errMessage(primaryError)}`)
    console.warn(`[ai] ↪️  Falling back to ${FALLBACK_LABEL}`)

    // ---- Fallback: OpenRouter ----
    const backup = streamText({
        ...params,
        model: fallback,
        onError: () => {},
    })

    for await (const part of backup.fullStream) {
        if (part.type === 'text-delta') {
            yield part.text
        } else if (part.type === 'error') {
            console.error(
                `[ai] ❌ ${FALLBACK_LABEL} also failed: ${errMessage(part.error)}`
            )
            throw asError(part.error)
        }
    }

    console.log(`[ai] ✅ Response generated by: ${FALLBACK_LABEL}`)
}

/**
 * `generateObject` with the same Gemini -> OpenRouter fallback behaviour.
 * `generateObject` rejects on error, so a simple try/catch is enough here.
 * Falls back on ANY Gemini error. Logs which model produced the response.
 */
export async function generateObjectWithFallback<
    P extends Omit<Parameters<typeof generateObject>[0], 'model'>,
>(params: P) {
    try {
        const result = await generateObject({
            ...params,
            model: primaryModel(),
        } as Parameters<typeof generateObject>[0])
        console.log(`[ai] ✅ Response generated by: ${PRIMARY_LABEL}`)
        return result
    } catch (error) {
        const fallback = fallbackModel()
        if (!fallback) {
            console.error(
                `[ai] ❌ ${PRIMARY_LABEL} failed and no OPENROUTER_API_KEY configured: ${errMessage(error)}`
            )
            throw error
        }

        console.warn(`[ai] ⚠️  ${PRIMARY_LABEL} failed: ${errMessage(error)}`)
        console.warn(`[ai] ↪️  Falling back to ${FALLBACK_LABEL}`)

        const result = await generateObject({
            ...params,
            model: fallback,
        } as Parameters<typeof generateObject>[0])
        console.log(`[ai] ✅ Response generated by: ${FALLBACK_LABEL}`)
        return result
    }
}
